/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion2_lab6;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KATHERINE
 */
public class Donas_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Donas_Principal
     */
    public Donas_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productos_comida = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rb_donas = new javax.swing.JRadioButton();
        rb_sandwich = new javax.swing.JRadioButton();
        rb_semitas = new javax.swing.JRadioButton();
        tf_nombre = new javax.swing.JTextField();
        tf_venta = new javax.swing.JTextField();
        tf_costo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_comidas = new javax.swing.JList<>();
        agregar_comida = new javax.swing.JButton();
        modificar_comida = new javax.swing.JButton();
        eliminar_comida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        productos_bebidas = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_costo2 = new javax.swing.JTextField();
        tf_venta2 = new javax.swing.JTextField();
        tf_tamaño2 = new javax.swing.JTextField();
        rb_helado = new javax.swing.JRadioButton();
        rb_caliente = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        tf_nombre2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rb_cafe = new javax.swing.JRadioButton();
        rb_jug = new javax.swing.JRadioButton();
        rb_te = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_bebidas = new javax.swing.JList<>();
        agregar_bebidas = new javax.swing.JButton();
        modificar_bebidas = new javax.swing.JButton();
        eliminarbebidas = new javax.swing.JButton();
        tipos_comida = new javax.swing.ButtonGroup();
        estado_bebida = new javax.swing.ButtonGroup();
        tipo_bebida = new javax.swing.ButtonGroup();
        facturas = new javax.swing.JDialog();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ventas = new javax.swing.JDialog();
        Crear_fact = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_escoger = new javax.swing.JList<>();
        cargar_arreglo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        abrir_inve = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        texa = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        tabla = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        comidas = new javax.swing.JMenuItem();
        bebidas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        registrar_venta = new javax.swing.JMenuItem();
        guardar_venta = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        productos_comida.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Comidas");
        productos_comida.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 69, 44));

        jLabel2.setText("Precio costo");
        productos_comida.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 109, -1, -1));

        jLabel3.setText("Precio venta");
        productos_comida.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 201, -1, -1));

        jLabel4.setText("Nombre");
        productos_comida.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 285, -1, -1));

        jLabel5.setText("Tipo de comida");
        productos_comida.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        tipos_comida.add(rb_donas);
        rb_donas.setSelected(true);
        rb_donas.setText("Donas");
        rb_donas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_donasActionPerformed(evt);
            }
        });
        productos_comida.getContentPane().add(rb_donas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        tipos_comida.add(rb_sandwich);
        rb_sandwich.setText("Sandwich");
        productos_comida.getContentPane().add(rb_sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        tipos_comida.add(rb_semitas);
        rb_semitas.setText("Semitas");
        productos_comida.getContentPane().add(rb_semitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));
        productos_comida.getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 282, 163, -1));
        productos_comida.getContentPane().add(tf_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 200, 163, -1));
        productos_comida.getContentPane().add(tf_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 106, 163, -1));

        jl_comidas.setModel(new DefaultListModel()
        );
        jScrollPane1.setViewportView(jl_comidas);

        productos_comida.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 520, 143));

        agregar_comida.setText("Agregar");
        agregar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_comidaMouseClicked(evt);
            }
        });
        productos_comida.getContentPane().add(agregar_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        modificar_comida.setText("Modificar");
        modificar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificar_comidaMouseClicked(evt);
            }
        });
        productos_comida.getContentPane().add(modificar_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        eliminar_comida.setText("Eliminar");
        eliminar_comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_comidaMouseClicked(evt);
            }
        });
        productos_comida.getContentPane().add(eliminar_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programacion2_lab6/donas-caseras.jpg"))); // NOI18N
        productos_comida.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 520));
        productos_comida.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 90));

        jLabel7.setText("Bebidas");

        jLabel8.setText("Precio de costo");

        jLabel9.setText("Precio de venta");

        jLabel10.setText("Nombre");

        jLabel11.setText("Estado");

        estado_bebida.add(rb_helado);
        rb_helado.setSelected(true);
        rb_helado.setText("helado");

        estado_bebida.add(rb_caliente);
        rb_caliente.setText("caliente");

        jLabel12.setText("Tamaño");

        jLabel13.setText("Tipo");

        tipo_bebida.add(rb_cafe);
        rb_cafe.setSelected(true);
        rb_cafe.setText("Cafe");

        tipo_bebida.add(rb_jug);
        rb_jug.setText("Jugo");

        tipo_bebida.add(rb_te);
        rb_te.setText("té verde");

        jl_bebidas.setModel(new DefaultListModel()
        );
        jScrollPane2.setViewportView(jl_bebidas);

        agregar_bebidas.setText("Agregar");
        agregar_bebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_bebidasMouseClicked(evt);
            }
        });

        modificar_bebidas.setText("modificar");
        modificar_bebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificar_bebidasMouseClicked(evt);
            }
        });

        eliminarbebidas.setText("jButton3");
        eliminarbebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarbebidasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productos_bebidasLayout = new javax.swing.GroupLayout(productos_bebidas.getContentPane());
        productos_bebidas.getContentPane().setLayout(productos_bebidasLayout);
        productos_bebidasLayout.setHorizontalGroup(
            productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productos_bebidasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productos_bebidasLayout.createSequentialGroup()
                        .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_costo2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productos_bebidasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_tamaño2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productos_bebidasLayout.createSequentialGroup()
                        .addComponent(rb_cafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_jug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_te))
                    .addGroup(productos_bebidasLayout.createSequentialGroup()
                        .addComponent(rb_helado)
                        .addGap(18, 18, 18)
                        .addComponent(rb_caliente))
                    .addComponent(tf_venta2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productos_bebidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(productos_bebidasLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(agregar_bebidas)
                .addGap(137, 137, 137)
                .addComponent(modificar_bebidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarbebidas)
                .addGap(106, 106, 106))
            .addGroup(productos_bebidasLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productos_bebidasLayout.setVerticalGroup(
            productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productos_bebidasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_helado)
                        .addComponent(rb_caliente))
                    .addGroup(productos_bebidasLayout.createSequentialGroup()
                        .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(tf_costo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_venta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(46, 46, 46)
                .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_tamaño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(rb_cafe)
                    .addComponent(rb_jug)
                    .addComponent(rb_te))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(productos_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_bebidas)
                    .addComponent(modificar_bebidas)
                    .addComponent(eliminarbebidas))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jMenu4.setText("FACTURA");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Crear factura");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Guardar factura");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);
        jMenuBar2.add(jMenu5);

        facturas.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout facturasLayout = new javax.swing.GroupLayout(facturas.getContentPane());
        facturas.getContentPane().setLayout(facturasLayout);
        facturasLayout.setHorizontalGroup(
            facturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        facturasLayout.setVerticalGroup(
            facturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ventasLayout = new javax.swing.GroupLayout(ventas.getContentPane());
        ventas.getContentPane().setLayout(ventasLayout);
        ventasLayout.setHorizontalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ventasLayout.setVerticalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jl_escoger.setModel(new DefaultListModel()
        );
        jScrollPane3.setViewportView(jl_escoger);

        cargar_arreglo.setText("AGREGAR AL CARRITO");
        cargar_arreglo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargar_arregloMouseClicked(evt);
            }
        });

        jButton1.setText("CREAR LA FACTURA");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Crear_factLayout = new javax.swing.GroupLayout(Crear_fact.getContentPane());
        Crear_fact.getContentPane().setLayout(Crear_factLayout);
        Crear_factLayout.setHorizontalGroup(
            Crear_factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_factLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cargar_arreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_factLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        Crear_factLayout.setVerticalGroup(
            Crear_factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_factLayout.createSequentialGroup()
                .addGroup(Crear_factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_factLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(cargar_arreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Crear_factLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        texa.setColumns(20);
        texa.setRows(5);
        jScrollPane4.setViewportView(texa);

        jButton2.setText("abrir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout abrir_inveLayout = new javax.swing.GroupLayout(abrir_inve.getContentPane());
        abrir_inve.getContentPane().setLayout(abrir_inveLayout);
        abrir_inveLayout.setHorizontalGroup(
            abrir_inveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrir_inveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abrir_inveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        abrir_inveLayout.setVerticalGroup(
            abrir_inveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abrir_inveLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Total factura neto", "impuesto", "fecha"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jButton3.setText("generar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tablaLayout = new javax.swing.GroupLayout(tabla.getContentPane());
        tabla.getContentPane().setLayout(tablaLayout);
        tablaLayout.setHorizontalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaLayout.createSequentialGroup()
                .addGroup(tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tablaLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        tablaLayout.setVerticalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programacion2_lab6/dunkin-donuts.jpg"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 83, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        jMenu1.setText("Dunkin Donuts ");

        jMenu3.setText("Productos");

        comidas.setText("Comidas ");
        comidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidasActionPerformed(evt);
            }
        });
        jMenu3.add(comidas);

        bebidas.setText("Bebidas");
        bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidasActionPerformed(evt);
            }
        });
        jMenu3.add(bebidas);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Facturas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu8.setText("Inventario");

        jMenuItem8.setText("abrir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem9.setText("guardar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenu1.add(jMenu8);

        jMenu6.setText("Venta");

        registrar_venta.setText("Registrar");
        registrar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_ventaActionPerformed(evt);
            }
        });
        jMenu6.add(registrar_venta);

        guardar_venta.setText("guardar ");
        guardar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_ventaActionPerformed(evt);
            }
        });
        jMenu6.add(guardar_venta);

        jMenu1.add(jMenu6);

        jMenu7.setText("Ingresos");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu7);

        jMenuItem2.setText("Listar tabla de ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidasActionPerformed
        // TODO add your handling code here:
        productos_bebidas .setModal(true);
        productos_bebidas.pack();
        productos_bebidas.setLocationRelativeTo(this);
        productos_bebidas.setVisible(true);
    }//GEN-LAST:event_bebidasActionPerformed

    private void comidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidasActionPerformed
        // TODO add your handling code here:
         productos_comida .setModal(true);
        productos_comida.pack();
        productos_comida.setLocationRelativeTo(this);
        productos_comida.setVisible(true);
        
    }//GEN-LAST:event_comidasActionPerformed

    private void agregar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_comidaMouseClicked
        // TODO add your handling code here:
        Inventario inve=new Inventario();
        double precio_costo;
        double precio_venta;
        String nombre;
        String tipo;
        try {
            precio_costo=Double.parseDouble(tf_costo.getText());
            precio_venta=Double.parseDouble(tf_venta.getText());
            nombre=tf_nombre.getText();
            if(rb_donas.isSelected()){
                tipo="dona";
                
            }else{
                if(rb_sandwich.isSelected()){
                    tipo="sandwich";
                    
                }else{
                    tipo="semitas";
                }
            }
            
            
            
            inve2.setProductos(new Comidas(tipo, precio_costo, precio_venta, nombre));
            System.out.println(inve2);
            
            
            JOptionPane.showMessageDialog(productos_comida, "se agrego la comida exitosamente");
               DefaultListModel modelo=(DefaultListModel)jl_comidas.getModel();
            modelo.addElement(new Comidas(tipo, precio_costo, precio_venta, nombre));
            
             DefaultListModel modelo2=(DefaultListModel)jl_escoger.getModel();
            modelo2.addElement(new Comidas(tipo, precio_costo, precio_venta, nombre));
            
           jl_comidas.setModel(modelo);
           
           
           tf_costo.setText("");
           tf_venta.setText("");
           tf_nombre.setText("");
           
            
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(productos_comida, "Ocurrió un Error");
        }
    }//GEN-LAST:event_agregar_comidaMouseClicked

    private void rb_donasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_donasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_donasActionPerformed

    private void modificar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_comidaMouseClicked
      
        
        int d=jl_comidas.getSelectedIndex();
        if(d>=0){
            double precio_venta=Double.parseDouble(JOptionPane.showInputDialog("nuevo precio de venta"));
            double precio_costo=Double.parseDouble(JOptionPane.showInputDialog("nuevo precio de costo"));
            String  nombre=JOptionPane.showInputDialog("nuevo nombre");
            String tipo;
            int t=Integer.parseInt(JOptionPane.showInputDialog("nuevo tipo:\n"
                    + "1.dona\n"
                    + "2.sandwich\n"
                    + "3.semitas"));
            if(t==1){
                tipo="dona";
               
            }else{
                if(t==2){
                    tipo="sandwich";
                }else{
                    tipo="semitas";
                }
            }
             DefaultListModel modelo = (DefaultListModel)jl_comidas.getModel();
              ((Comidas)modelo.get(d)).setTipo_comida(tipo);
              jl_comidas.setModel(modelo);
              
              producto.get(d).setPrecio_venta(precio_venta);
              producto.get(d).setPrecio_costo(precio_costo);
              producto.get(d).setNombre(nombre);
              ((Comidas)producto.get(d)).setTipo_comida(tipo);
              
            
        }else{
            JOptionPane.showMessageDialog(productos_comida, "fila no seleccionada");
        }
    }//GEN-LAST:event_modificar_comidaMouseClicked

    private void eliminar_comidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_comidaMouseClicked
        // TODO add your handling code here:
 DefaultListModel modelo = (DefaultListModel)jl_comidas.getModel(); 
 int i=jl_comidas.getSelectedIndex();
        modelo.remove(i);
        producto.remove(i);
    }//GEN-LAST:event_eliminar_comidaMouseClicked

    private void agregar_bebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_bebidasMouseClicked
       Inventario inve=new Inventario();
        double precio_costo;
        double precio_venta;
        String nombre;
        String tamaño;
        String estado;
        String tipo;
        try {
            precio_costo=Double.parseDouble(tf_costo2.getText());
            precio_venta=Double.parseDouble(tf_venta2.getText());
            nombre=tf_nombre2.getText();
            tamaño=tf_tamaño2.getText();
            if(rb_caliente.isSelected()){
                estado="caliente";
            }else{
                estado="helado";
                
            }
            if(rb_cafe.isSelected()){
                tipo="cafe";
            }else{
                if(rb_jug.isSelected()){
                    tipo="jugo";
                }else{
                    tipo="té verde";
                }
            }
                    //String estado, String tamaño, String tipo, double precio_costo, double precio_venta, String nombre
            
            
            inve2.setProductos(new Bebidas(estado, tamaño, tipo, precio_costo, precio_venta, nombre));
            System.out.println(inve2.getProductos());
            
            
            JOptionPane.showMessageDialog(productos_bebidas, "se agrego la bebida exitosamente");
               DefaultListModel modelo=(DefaultListModel)jl_bebidas.getModel();
            modelo.addElement(new Bebidas(estado, tamaño, tipo, precio_costo, precio_venta, nombre));
            
            DefaultListModel modelo2=(DefaultListModel)jl_escoger.getModel();
            modelo2.addElement(new Bebidas(estado, tamaño, tipo, precio_costo, precio_venta, nombre));
            
            
           jl_comidas.setModel(modelo);
           
         
           tf_costo2.setText("");
           tf_venta2.setText("");
           tf_nombre2.setText("");
           tf_tamaño2.setText("");
           
            
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(productos_comida, "Ocurrió un Error");
        }
    }//GEN-LAST:event_agregar_bebidasMouseClicked

    private void modificar_bebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_bebidasMouseClicked
        // TODO add your handling code here:
         int d=jl_bebidas.getSelectedIndex();
        if(d>=0){
            /*
            double precio_costo;
        double precio_venta;
        String nombre;
        String tamaño;
        String estado;
        String tipo;
            */
            double precio_venta=Double.parseDouble(JOptionPane.showInputDialog("nuevo precio de venta"));
            double precio_costo=Double.parseDouble(JOptionPane.showInputDialog("nuevo precio de costo"));
            String  nombre=JOptionPane.showInputDialog("nuevo nombre");
            String  tamaño=JOptionPane.showInputDialog("nuevo tamaño");
            String tipo;
            int t=Integer.parseInt(JOptionPane.showInputDialog("nuevo tipo:\n"
                    + "1.Cafe\n"
                    + "2.Jugo\n"
                    + "3.té verde"));
            if(t==1){
                tipo="cafe";
               
            }else{
                if(t==2){
                    tipo="jugo";
                }else{
                    tipo="té verde";
                }
            }
            String estado;
            int x=Integer.parseInt(JOptionPane.showInputDialog("nuevo estado de la bebida:\n"
                    +"1.caliente\n"
                    + "2.helado"));
            if(x==1){
                estado="caliente";
            }else{
                estado="helado";
            }
            
             DefaultListModel modelo = (DefaultListModel)jl_bebidas.getModel();
              ((Bebidas)modelo.get(d)).setTipo(tipo);
              jl_bebidas.setModel(modelo);
              
              producto.get(d).setPrecio_venta(precio_venta);
              producto.get(d).setPrecio_costo(precio_costo);
              producto.get(d).setNombre(nombre);
              ((Bebidas)producto.get(d)).setTamaño(tamaño);
              ((Bebidas)producto.get(d)).setEstado(estado);
              ((Bebidas)producto.get(d)).setTipo(tipo);
              
            
        }else{
            JOptionPane.showMessageDialog(productos_comida, "fila no seleccionada");
        }
        
    }//GEN-LAST:event_modificar_bebidasMouseClicked

    private void eliminarbebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarbebidasMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel)jl_bebidas.getModel(); 
 int i=jl_bebidas.getSelectedIndex();
        modelo.remove(i);
        producto.remove(i);
    }//GEN-LAST:event_eliminarbebidasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         facturas .setModal(true);
        facturas.pack();
        facturas.setLocationRelativeTo(this);
        facturas.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
JFileChooser jfc=new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        
        int seleccion=jfc.showSaveDialog(this);
        
        FileWriter fw=null;
        BufferedWriter bw=null;
        
        if(seleccion==JFileChooser.APPROVE_OPTION){
            try {
               File fichero=null;
               //capturar el tipo que fue seleccionadpo
               if(jfc.getFileFilter().getDescription().equals("Archivos de Texto")){
                   fichero=new File(jfc.getSelectedFile().getPath()+".txt");
                   
               }else{
                   fichero=jfc.getSelectedFile();
               }
               fw=new FileWriter(fichero);
               bw=new BufferedWriter(fw);
               bw.write(factura);
//               fa.setText("");
               bw.flush();
             
               JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
               
            } catch (Exception e) {
                 e.printStackTrace();
            }
        }        // TODO add your handling code here:
        
        
                  
        
          
          
          
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
         //crear factura
        
        Productos produc=new Productos();
        //guardar factura
        double total=0;
        String muestra_produc="";
        System.out.println(inve2.getProductos().size());
        for (int i = 0; i <inve2.getProductos().size() ; i++) {
            total+=inve2.getProductos().get(i).getPrecio_venta();
            muestra_produc+=inve2.getProductos().get(i).getNombre()+"   "+inve2.getProductos().get(i).getPrecio_venta()+"\n";
        }
        double subtotal=produc.IVS(total);
        double impuestos=produc.impuesto(subtotal);
         total_final=subtotal+impuestos;//total
        
        
        String CAI=JOptionPane.showInputDialog("ingrese CAI:");
         String RTN=JOptionPane.showInputDialog("ingrese RTN:");
        fecha_factura=JOptionPane.showInputDialog("ingrese fecha");
         String correo=JOptionPane.showInputDialog("ingrese correo");
          String nombre_cliente=JOptionPane.showInputDialog("ingrese nombre de cliente");
          
          fact.setNombre_cliente(nombre_cliente);
          fact.setCAI(CAI);
          fact.setCorreo(correo);
          fact.setRTN(RTN);
          fact.setCAI(CAI);
          fact.setFecha(fecha_factura);
         factura=fact.facturita(muestra_produc, subtotal, impuestos, total_final);
          
          JOptionPane.showMessageDialog(Crear_fact, "factura creada exitosamente"+" \n"+
                  factura);
          System.out.println(factura);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
  Crear_fact .setModal(true);
        Crear_fact.pack();
        Crear_fact.setLocationRelativeTo(this);
        Crear_fact.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void cargar_arregloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargar_arregloMouseClicked
        // TODO add your handling code here:
        //AGREGAR AL CARRITO
        int d=jl_escoger.getSelectedIndex();
        if(d>=0){
//            Object x=inve2.getProductos().get(d).getNombre();
//            arreglo.add(x);
//            System.out.println(arreglo);
            fact.getProductos().add(inve2.getProductos().get(d));
            
            
            JOptionPane.showMessageDialog(Crear_fact, "se agregó al carrito");
        }else{
            JOptionPane.showMessageDialog(Crear_fact, "fila no selecionada");
        }
    }//GEN-LAST:event_cargar_arregloMouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
       //guardar inventario
        String muestra_produc="";
       for (int i = 0; i <inve2.getProductos().size() ; i++) {
            
            muestra_produc+=inve2.getProductos().get(i);
        }
       
        try {
            inve2.guardar(muestra_produc);
            JOptionPane.showMessageDialog(this, "Se guardo el inventario exitosamente"
                + "");
        } catch (IOException ex) {
            Logger.getLogger(Donas_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void registrar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_ventaActionPerformed
        // TODO add your handling code here:
        ingre.setVentas(new Ventas(total_final,fecha_factura));
        JOptionPane.showMessageDialog(this, "Se registro la venta exitosamente"
                + "");
    }//GEN-LAST:event_registrar_ventaActionPerformed

    private void guardar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_ventaActionPerformed
        // TODO add your handling code here:
        //guardar venta
          String muestra_produc="";
       for (int i = 0; i <ingre.getVentas().size() ; i++) {
            
            muestra_produc+=ingre.getVentas().get(i);
        }
       
        try {
            inve2.guardar(muestra_produc);
            JOptionPane.showMessageDialog(this, "Se guadro la venta exitosamente"
                + "");
        } catch (IOException ex) {
            Logger.getLogger(Donas_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_guardar_ventaActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
       tabla .setModal(true);
        tabla.pack();
        tabla.setLocationRelativeTo(this);
        tabla.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        abrir_inve .setModal(true);
        abrir_inve.pack();
        abrir_inve.setLocationRelativeTo(this);
        abrir_inve.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         File fichero=null;
        FileReader fr=null;
        BufferedReader br=null;
        texa.setText("");
        try {
            JFileChooser jfc=new JFileChooser();
            //JFileChooser jfc=new JFileChooser("./");//Desde el directorio del proyecto
            FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivos de texto","txt");
            
            
           
            
            
            //ponerlo en el combobox
            jfc.setFileFilter(filtro);//lo deja marcado por defecto
          
            //----------------------
            int seleccion=jfc.showOpenDialog(this);//Abrir archivo
            if(seleccion==JFileChooser.APPROVE_OPTION){
                fichero=jfc.getSelectedFile();
                fr=new FileReader(fichero);
                
                br=new BufferedReader(fr);
                String linea;
                texa.setText("");
                while((linea=br.readLine())!= null){
                 
                    texa.append(linea);
                    texa.append("\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donas_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donas_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donas_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donas_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donas_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear_fact;
    private javax.swing.JDialog abrir_inve;
    private javax.swing.JButton agregar_bebidas;
    private javax.swing.JButton agregar_comida;
    private javax.swing.JMenuItem bebidas;
    private javax.swing.JButton cargar_arreglo;
    private javax.swing.JMenuItem comidas;
    private javax.swing.JButton eliminar_comida;
    private javax.swing.JButton eliminarbebidas;
    private javax.swing.ButtonGroup estado_bebida;
    private javax.swing.JDialog facturas;
    private javax.swing.JMenuItem guardar_venta;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> jl_bebidas;
    private javax.swing.JList<String> jl_comidas;
    private javax.swing.JList<String> jl_escoger;
    private javax.swing.JButton modificar_bebidas;
    private javax.swing.JButton modificar_comida;
    private javax.swing.JDialog productos_bebidas;
    private javax.swing.JDialog productos_comida;
    private javax.swing.JRadioButton rb_cafe;
    private javax.swing.JRadioButton rb_caliente;
    private javax.swing.JRadioButton rb_donas;
    private javax.swing.JRadioButton rb_helado;
    private javax.swing.JRadioButton rb_jug;
    private javax.swing.JRadioButton rb_sandwich;
    private javax.swing.JRadioButton rb_semitas;
    private javax.swing.JRadioButton rb_te;
    private javax.swing.JMenuItem registrar_venta;
    private javax.swing.JDialog tabla;
    private javax.swing.JTextArea texa;
    private javax.swing.JTextField tf_costo;
    private javax.swing.JTextField tf_costo2;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_tamaño2;
    private javax.swing.JTextField tf_venta;
    private javax.swing.JTextField tf_venta2;
    private javax.swing.ButtonGroup tipo_bebida;
    private javax.swing.ButtonGroup tipos_comida;
    private javax.swing.JDialog ventas;
    // End of variables declaration//GEN-END:variables

ArrayList<Productos> producto=new ArrayList();
Inventario inve2 = new Inventario();
Ingresos ingre=new Ingresos();
    ArrayList arreglo=new ArrayList();
    Factura fact=new Factura();
    String factura,fecha_factura;
    double total_final;
    
}
